// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/quantum-platform/backend/db/skill"
	"github.com/ghshhf/quantum-platform/backend/db/team"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroup"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroupskill"
	"github.com/ghshhf/quantum-platform/backend/db/teamskill"
	"github.com/ghshhf/quantum-platform/backend/db/user"
	"github.com/google/uuid"
)

// SkillCreate is the builder for creating a Skill entity.
type SkillCreate struct {
	config
	mutation *SkillMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SkillCreate) SetDeletedAt(v time.Time) *SkillCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableDeletedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SkillCreate) SetUserID(v uuid.UUID) *SkillCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SkillCreate) SetName(v string) *SkillCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SkillCreate) SetDescription(v string) *SkillCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *SkillCreate) SetTags(v []string) *SkillCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SkillCreate) SetContent(v string) *SkillCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetPackageObjectKey sets the "package_object_key" field.
func (_c *SkillCreate) SetPackageObjectKey(v string) *SkillCreate {
	_c.mutation.SetPackageObjectKey(v)
	return _c
}

// SetNillablePackageObjectKey sets the "package_object_key" field if the given value is not nil.
func (_c *SkillCreate) SetNillablePackageObjectKey(v *string) *SkillCreate {
	if v != nil {
		_c.SetPackageObjectKey(*v)
	}
	return _c
}

// SetPackageURL sets the "package_url" field.
func (_c *SkillCreate) SetPackageURL(v string) *SkillCreate {
	_c.mutation.SetPackageURL(v)
	return _c
}

// SetNillablePackageURL sets the "package_url" field if the given value is not nil.
func (_c *SkillCreate) SetNillablePackageURL(v *string) *SkillCreate {
	if v != nil {
		_c.SetPackageURL(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *SkillCreate) SetSourceType(v string) *SkillCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceLabel sets the "source_label" field.
func (_c *SkillCreate) SetSourceLabel(v string) *SkillCreate {
	_c.mutation.SetSourceLabel(v)
	return _c
}

// SetSkillMdPath sets the "skill_md_path" field.
func (_c *SkillCreate) SetSkillMdPath(v string) *SkillCreate {
	_c.mutation.SetSkillMdPath(v)
	return _c
}

// SetNillableSkillMdPath sets the "skill_md_path" field if the given value is not nil.
func (_c *SkillCreate) SetNillableSkillMdPath(v *string) *SkillCreate {
	if v != nil {
		_c.SetSkillMdPath(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SkillCreate) SetCreatedAt(v time.Time) *SkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableCreatedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SkillCreate) SetUpdatedAt(v time.Time) *SkillCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableUpdatedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SkillCreate) SetID(v uuid.UUID) *SkillCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SkillCreate) SetUser(v *User) *SkillCreate {
	return _c.SetUserID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_c *SkillCreate) AddTeamIDs(ids ...uuid.UUID) *SkillCreate {
	_c.mutation.AddTeamIDs(ids...)
	return _c
}

// AddTeams adds the "teams" edges to the Team entity.
func (_c *SkillCreate) AddTeams(v ...*Team) *SkillCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the TeamGroup entity by IDs.
func (_c *SkillCreate) AddGroupIDs(ids ...uuid.UUID) *SkillCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the TeamGroup entity.
func (_c *SkillCreate) AddGroups(v ...*TeamGroup) *SkillCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddTeamSkillIDs adds the "team_skills" edge to the TeamSkill entity by IDs.
func (_c *SkillCreate) AddTeamSkillIDs(ids ...uuid.UUID) *SkillCreate {
	_c.mutation.AddTeamSkillIDs(ids...)
	return _c
}

// AddTeamSkills adds the "team_skills" edges to the TeamSkill entity.
func (_c *SkillCreate) AddTeamSkills(v ...*TeamSkill) *SkillCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamSkillIDs(ids...)
}

// AddTeamGroupSkillIDs adds the "team_group_skills" edge to the TeamGroupSkill entity by IDs.
func (_c *SkillCreate) AddTeamGroupSkillIDs(ids ...uuid.UUID) *SkillCreate {
	_c.mutation.AddTeamGroupSkillIDs(ids...)
	return _c
}

// AddTeamGroupSkills adds the "team_group_skills" edges to the TeamGroupSkill entity.
func (_c *SkillCreate) AddTeamGroupSkills(v ...*TeamGroupSkill) *SkillCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamGroupSkillIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_c *SkillCreate) Mutation() *SkillMutation {
	return _c.mutation
}

// Save creates the Skill in the database.
func (_c *SkillCreate) Save(ctx context.Context) (*Skill, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SkillCreate) SaveX(ctx context.Context) *Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SkillCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if skill.DefaultCreatedAt == nil {
			return fmt.Errorf("db: uninitialized skill.DefaultCreatedAt (forgotten import db/runtime?)")
		}
		v := skill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if skill.DefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized skill.DefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := skill.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SkillCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`db: missing required field "Skill.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Skill.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`db: missing required field "Skill.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := skill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`db: validator failed for field "Skill.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`db: missing required field "Skill.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`db: validator failed for field "Skill.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`db: missing required field "Skill.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := skill.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`db: validator failed for field "Skill.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceLabel(); !ok {
		return &ValidationError{Name: "source_label", err: errors.New(`db: missing required field "Skill.source_label"`)}
	}
	if v, ok := _c.mutation.SourceLabel(); ok {
		if err := skill.SourceLabelValidator(v); err != nil {
			return &ValidationError{Name: "source_label", err: fmt.Errorf(`db: validator failed for field "Skill.source_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Skill.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Skill.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`db: missing required edge "Skill.user"`)}
	}
	return nil
}

func (_c *SkillCreate) sqlSave(ctx context.Context) (*Skill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SkillCreate) createSpec() (*Skill, *sqlgraph.CreateSpec) {
	var (
		_node = &Skill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(skill.Table, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(skill.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(skill.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.PackageObjectKey(); ok {
		_spec.SetField(skill.FieldPackageObjectKey, field.TypeString, value)
		_node.PackageObjectKey = value
	}
	if value, ok := _c.mutation.PackageURL(); ok {
		_spec.SetField(skill.FieldPackageURL, field.TypeString, value)
		_node.PackageURL = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(skill.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceLabel(); ok {
		_spec.SetField(skill.FieldSourceLabel, field.TypeString, value)
		_node.SourceLabel = value
	}
	if value, ok := _c.mutation.SkillMdPath(); ok {
		_spec.SetField(skill.FieldSkillMdPath, field.TypeString, value)
		_node.SkillMdPath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamSkillCreate{config: _c.config, mutation: newTeamSkillMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamGroupSkillCreate{config: _c.config, mutation: newTeamGroupSkillMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamGroupSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Skill.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SkillUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SkillCreate) OnConflict(opts ...sql.ConflictOption) *SkillUpsertOne {
	_c.conflict = opts
	return &SkillUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Skill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SkillCreate) OnConflictColumns(columns ...string) *SkillUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SkillUpsertOne{
		create: _c,
	}
}

type (
	// SkillUpsertOne is the builder for "upsert"-ing
	//  one Skill node.
	SkillUpsertOne struct {
		create *SkillCreate
	}

	// SkillUpsert is the "OnConflict" setter.
	SkillUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *SkillUpsert) SetDeletedAt(v time.Time) *SkillUpsert {
	u.Set(skill.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SkillUpsert) UpdateDeletedAt() *SkillUpsert {
	u.SetExcluded(skill.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SkillUpsert) ClearDeletedAt() *SkillUpsert {
	u.SetNull(skill.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SkillUpsert) SetUserID(v uuid.UUID) *SkillUpsert {
	u.Set(skill.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SkillUpsert) UpdateUserID() *SkillUpsert {
	u.SetExcluded(skill.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *SkillUpsert) SetName(v string) *SkillUpsert {
	u.Set(skill.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SkillUpsert) UpdateName() *SkillUpsert {
	u.SetExcluded(skill.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SkillUpsert) SetDescription(v string) *SkillUpsert {
	u.Set(skill.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SkillUpsert) UpdateDescription() *SkillUpsert {
	u.SetExcluded(skill.FieldDescription)
	return u
}

// SetTags sets the "tags" field.
func (u *SkillUpsert) SetTags(v []string) *SkillUpsert {
	u.Set(skill.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SkillUpsert) UpdateTags() *SkillUpsert {
	u.SetExcluded(skill.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *SkillUpsert) ClearTags() *SkillUpsert {
	u.SetNull(skill.FieldTags)
	return u
}

// SetContent sets the "content" field.
func (u *SkillUpsert) SetContent(v string) *SkillUpsert {
	u.Set(skill.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SkillUpsert) UpdateContent() *SkillUpsert {
	u.SetExcluded(skill.FieldContent)
	return u
}

// SetPackageObjectKey sets the "package_object_key" field.
func (u *SkillUpsert) SetPackageObjectKey(v string) *SkillUpsert {
	u.Set(skill.FieldPackageObjectKey, v)
	return u
}

// UpdatePackageObjectKey sets the "package_object_key" field to the value that was provided on create.
func (u *SkillUpsert) UpdatePackageObjectKey() *SkillUpsert {
	u.SetExcluded(skill.FieldPackageObjectKey)
	return u
}

// ClearPackageObjectKey clears the value of the "package_object_key" field.
func (u *SkillUpsert) ClearPackageObjectKey() *SkillUpsert {
	u.SetNull(skill.FieldPackageObjectKey)
	return u
}

// SetPackageURL sets the "package_url" field.
func (u *SkillUpsert) SetPackageURL(v string) *SkillUpsert {
	u.Set(skill.FieldPackageURL, v)
	return u
}

// UpdatePackageURL sets the "package_url" field to the value that was provided on create.
func (u *SkillUpsert) UpdatePackageURL() *SkillUpsert {
	u.SetExcluded(skill.FieldPackageURL)
	return u
}

// ClearPackageURL clears the value of the "package_url" field.
func (u *SkillUpsert) ClearPackageURL() *SkillUpsert {
	u.SetNull(skill.FieldPackageURL)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *SkillUpsert) SetSourceType(v string) *SkillUpsert {
	u.Set(skill.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SkillUpsert) UpdateSourceType() *SkillUpsert {
	u.SetExcluded(skill.FieldSourceType)
	return u
}

// SetSourceLabel sets the "source_label" field.
func (u *SkillUpsert) SetSourceLabel(v string) *SkillUpsert {
	u.Set(skill.FieldSourceLabel, v)
	return u
}

// UpdateSourceLabel sets the "source_label" field to the value that was provided on create.
func (u *SkillUpsert) UpdateSourceLabel() *SkillUpsert {
	u.SetExcluded(skill.FieldSourceLabel)
	return u
}

// SetSkillMdPath sets the "skill_md_path" field.
func (u *SkillUpsert) SetSkillMdPath(v string) *SkillUpsert {
	u.Set(skill.FieldSkillMdPath, v)
	return u
}

// UpdateSkillMdPath sets the "skill_md_path" field to the value that was provided on create.
func (u *SkillUpsert) UpdateSkillMdPath() *SkillUpsert {
	u.SetExcluded(skill.FieldSkillMdPath)
	return u
}

// ClearSkillMdPath clears the value of the "skill_md_path" field.
func (u *SkillUpsert) ClearSkillMdPath() *SkillUpsert {
	u.SetNull(skill.FieldSkillMdPath)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SkillUpsert) SetCreatedAt(v time.Time) *SkillUpsert {
	u.Set(skill.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SkillUpsert) UpdateCreatedAt() *SkillUpsert {
	u.SetExcluded(skill.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SkillUpsert) SetUpdatedAt(v time.Time) *SkillUpsert {
	u.Set(skill.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SkillUpsert) UpdateUpdatedAt() *SkillUpsert {
	u.SetExcluded(skill.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Skill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(skill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SkillUpsertOne) UpdateNewValues() *SkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(skill.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Skill.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SkillUpsertOne) Ignore() *SkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SkillUpsertOne) DoNothing() *SkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SkillCreate.OnConflict
// documentation for more info.
func (u *SkillUpsertOne) Update(set func(*SkillUpsert)) *SkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SkillUpsertOne) SetDeletedAt(v time.Time) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateDeletedAt() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SkillUpsertOne) ClearDeletedAt() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SkillUpsertOne) SetUserID(v uuid.UUID) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateUserID() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *SkillUpsertOne) SetName(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateName() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SkillUpsertOne) SetDescription(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateDescription() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *SkillUpsertOne) SetTags(v []string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateTags() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *SkillUpsertOne) ClearTags() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.ClearTags()
	})
}

// SetContent sets the "content" field.
func (u *SkillUpsertOne) SetContent(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateContent() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateContent()
	})
}

// SetPackageObjectKey sets the "package_object_key" field.
func (u *SkillUpsertOne) SetPackageObjectKey(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetPackageObjectKey(v)
	})
}

// UpdatePackageObjectKey sets the "package_object_key" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdatePackageObjectKey() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdatePackageObjectKey()
	})
}

// ClearPackageObjectKey clears the value of the "package_object_key" field.
func (u *SkillUpsertOne) ClearPackageObjectKey() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.ClearPackageObjectKey()
	})
}

// SetPackageURL sets the "package_url" field.
func (u *SkillUpsertOne) SetPackageURL(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetPackageURL(v)
	})
}

// UpdatePackageURL sets the "package_url" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdatePackageURL() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdatePackageURL()
	})
}

// ClearPackageURL clears the value of the "package_url" field.
func (u *SkillUpsertOne) ClearPackageURL() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.ClearPackageURL()
	})
}

// SetSourceType sets the "source_type" field.
func (u *SkillUpsertOne) SetSourceType(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateSourceType() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceLabel sets the "source_label" field.
func (u *SkillUpsertOne) SetSourceLabel(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetSourceLabel(v)
	})
}

// UpdateSourceLabel sets the "source_label" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateSourceLabel() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSourceLabel()
	})
}

// SetSkillMdPath sets the "skill_md_path" field.
func (u *SkillUpsertOne) SetSkillMdPath(v string) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetSkillMdPath(v)
	})
}

// UpdateSkillMdPath sets the "skill_md_path" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateSkillMdPath() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSkillMdPath()
	})
}

// ClearSkillMdPath clears the value of the "skill_md_path" field.
func (u *SkillUpsertOne) ClearSkillMdPath() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.ClearSkillMdPath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SkillUpsertOne) SetCreatedAt(v time.Time) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateCreatedAt() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SkillUpsertOne) SetUpdatedAt(v time.Time) *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SkillUpsertOne) UpdateUpdatedAt() *SkillUpsertOne {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SkillUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for SkillCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SkillUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SkillUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: SkillUpsertOne.ID is not supported by MySQL driver. Use SkillUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SkillUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SkillCreateBulk is the builder for creating many Skill entities in bulk.
type SkillCreateBulk struct {
	config
	err      error
	builders []*SkillCreate
	conflict []sql.ConflictOption
}

// Save creates the Skill entities in the database.
func (_c *SkillCreateBulk) Save(ctx context.Context) ([]*Skill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Skill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SkillCreateBulk) SaveX(ctx context.Context) []*Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Skill.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SkillUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SkillCreateBulk) OnConflict(opts ...sql.ConflictOption) *SkillUpsertBulk {
	_c.conflict = opts
	return &SkillUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Skill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SkillCreateBulk) OnConflictColumns(columns ...string) *SkillUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SkillUpsertBulk{
		create: _c,
	}
}

// SkillUpsertBulk is the builder for "upsert"-ing
// a bulk of Skill nodes.
type SkillUpsertBulk struct {
	create *SkillCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Skill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(skill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SkillUpsertBulk) UpdateNewValues() *SkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(skill.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Skill.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SkillUpsertBulk) Ignore() *SkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SkillUpsertBulk) DoNothing() *SkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SkillCreateBulk.OnConflict
// documentation for more info.
func (u *SkillUpsertBulk) Update(set func(*SkillUpsert)) *SkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SkillUpsertBulk) SetDeletedAt(v time.Time) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateDeletedAt() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SkillUpsertBulk) ClearDeletedAt() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SkillUpsertBulk) SetUserID(v uuid.UUID) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateUserID() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *SkillUpsertBulk) SetName(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateName() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SkillUpsertBulk) SetDescription(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateDescription() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *SkillUpsertBulk) SetTags(v []string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateTags() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *SkillUpsertBulk) ClearTags() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.ClearTags()
	})
}

// SetContent sets the "content" field.
func (u *SkillUpsertBulk) SetContent(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateContent() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateContent()
	})
}

// SetPackageObjectKey sets the "package_object_key" field.
func (u *SkillUpsertBulk) SetPackageObjectKey(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetPackageObjectKey(v)
	})
}

// UpdatePackageObjectKey sets the "package_object_key" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdatePackageObjectKey() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdatePackageObjectKey()
	})
}

// ClearPackageObjectKey clears the value of the "package_object_key" field.
func (u *SkillUpsertBulk) ClearPackageObjectKey() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.ClearPackageObjectKey()
	})
}

// SetPackageURL sets the "package_url" field.
func (u *SkillUpsertBulk) SetPackageURL(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetPackageURL(v)
	})
}

// UpdatePackageURL sets the "package_url" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdatePackageURL() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdatePackageURL()
	})
}

// ClearPackageURL clears the value of the "package_url" field.
func (u *SkillUpsertBulk) ClearPackageURL() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.ClearPackageURL()
	})
}

// SetSourceType sets the "source_type" field.
func (u *SkillUpsertBulk) SetSourceType(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateSourceType() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceLabel sets the "source_label" field.
func (u *SkillUpsertBulk) SetSourceLabel(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetSourceLabel(v)
	})
}

// UpdateSourceLabel sets the "source_label" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateSourceLabel() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSourceLabel()
	})
}

// SetSkillMdPath sets the "skill_md_path" field.
func (u *SkillUpsertBulk) SetSkillMdPath(v string) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetSkillMdPath(v)
	})
}

// UpdateSkillMdPath sets the "skill_md_path" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateSkillMdPath() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateSkillMdPath()
	})
}

// ClearSkillMdPath clears the value of the "skill_md_path" field.
func (u *SkillUpsertBulk) ClearSkillMdPath() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.ClearSkillMdPath()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SkillUpsertBulk) SetCreatedAt(v time.Time) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateCreatedAt() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SkillUpsertBulk) SetUpdatedAt(v time.Time) *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SkillUpsertBulk) UpdateUpdatedAt() *SkillUpsertBulk {
	return u.Update(func(s *SkillUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SkillUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the SkillCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for SkillCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SkillUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
