// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/MonkeyCode/backend/db/predicate"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/team"
	"github.com/ghshhf/MonkeyCode/backend/db/teamgroup"
	"github.com/ghshhf/MonkeyCode/backend/db/teamgroupskill"
	"github.com/ghshhf/MonkeyCode/backend/db/teamskill"
	"github.com/ghshhf/MonkeyCode/backend/db/user"
	"github.com/google/uuid"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks     []Hook
	mutation  *SkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkillUpdate) SetDeletedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableDeletedAt(v *time.Time) *SkillUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SkillUpdate) ClearDeletedAt() *SkillUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SkillUpdate) SetUserID(v uuid.UUID) *SkillUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableUserID(v *uuid.UUID) *SkillUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdate) SetDescription(v string) *SkillUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableDescription(v *string) *SkillUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *SkillUpdate) SetTags(v []string) *SkillUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *SkillUpdate) AppendTags(v []string) *SkillUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *SkillUpdate) ClearTags() *SkillUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdate) SetContent(v string) *SkillUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableContent(v *string) *SkillUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPackageObjectKey sets the "package_object_key" field.
func (_u *SkillUpdate) SetPackageObjectKey(v string) *SkillUpdate {
	_u.mutation.SetPackageObjectKey(v)
	return _u
}

// SetNillablePackageObjectKey sets the "package_object_key" field if the given value is not nil.
func (_u *SkillUpdate) SetNillablePackageObjectKey(v *string) *SkillUpdate {
	if v != nil {
		_u.SetPackageObjectKey(*v)
	}
	return _u
}

// ClearPackageObjectKey clears the value of the "package_object_key" field.
func (_u *SkillUpdate) ClearPackageObjectKey() *SkillUpdate {
	_u.mutation.ClearPackageObjectKey()
	return _u
}

// SetPackageURL sets the "package_url" field.
func (_u *SkillUpdate) SetPackageURL(v string) *SkillUpdate {
	_u.mutation.SetPackageURL(v)
	return _u
}

// SetNillablePackageURL sets the "package_url" field if the given value is not nil.
func (_u *SkillUpdate) SetNillablePackageURL(v *string) *SkillUpdate {
	if v != nil {
		_u.SetPackageURL(*v)
	}
	return _u
}

// ClearPackageURL clears the value of the "package_url" field.
func (_u *SkillUpdate) ClearPackageURL() *SkillUpdate {
	_u.mutation.ClearPackageURL()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SkillUpdate) SetSourceType(v string) *SkillUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableSourceType(v *string) *SkillUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *SkillUpdate) SetSourceLabel(v string) *SkillUpdate {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableSourceLabel(v *string) *SkillUpdate {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetSkillMdPath sets the "skill_md_path" field.
func (_u *SkillUpdate) SetSkillMdPath(v string) *SkillUpdate {
	_u.mutation.SetSkillMdPath(v)
	return _u
}

// SetNillableSkillMdPath sets the "skill_md_path" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableSkillMdPath(v *string) *SkillUpdate {
	if v != nil {
		_u.SetSkillMdPath(*v)
	}
	return _u
}

// ClearSkillMdPath clears the value of the "skill_md_path" field.
func (_u *SkillUpdate) ClearSkillMdPath() *SkillUpdate {
	_u.mutation.ClearSkillMdPath()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdate) SetCreatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCreatedAt(v *time.Time) *SkillUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdate) SetUpdatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SkillUpdate) SetUser(v *User) *SkillUpdate {
	return _u.SetUserID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *SkillUpdate) AddTeamIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *SkillUpdate) AddTeams(v ...*Team) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the TeamGroup entity by IDs.
func (_u *SkillUpdate) AddGroupIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the TeamGroup entity.
func (_u *SkillUpdate) AddGroups(v ...*TeamGroup) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddTeamSkillIDs adds the "team_skills" edge to the TeamSkill entity by IDs.
func (_u *SkillUpdate) AddTeamSkillIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.AddTeamSkillIDs(ids...)
	return _u
}

// AddTeamSkills adds the "team_skills" edges to the TeamSkill entity.
func (_u *SkillUpdate) AddTeamSkills(v ...*TeamSkill) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamSkillIDs(ids...)
}

// AddTeamGroupSkillIDs adds the "team_group_skills" edge to the TeamGroupSkill entity by IDs.
func (_u *SkillUpdate) AddTeamGroupSkillIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.AddTeamGroupSkillIDs(ids...)
	return _u
}

// AddTeamGroupSkills adds the "team_group_skills" edges to the TeamGroupSkill entity.
func (_u *SkillUpdate) AddTeamGroupSkills(v ...*TeamGroupSkill) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamGroupSkillIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SkillUpdate) ClearUser() *SkillUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *SkillUpdate) ClearTeams() *SkillUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *SkillUpdate) RemoveTeamIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *SkillUpdate) RemoveTeams(v ...*Team) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearGroups clears all "groups" edges to the TeamGroup entity.
func (_u *SkillUpdate) ClearGroups() *SkillUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to TeamGroup entities by IDs.
func (_u *SkillUpdate) RemoveGroupIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to TeamGroup entities.
func (_u *SkillUpdate) RemoveGroups(v ...*TeamGroup) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearTeamSkills clears all "team_skills" edges to the TeamSkill entity.
func (_u *SkillUpdate) ClearTeamSkills() *SkillUpdate {
	_u.mutation.ClearTeamSkills()
	return _u
}

// RemoveTeamSkillIDs removes the "team_skills" edge to TeamSkill entities by IDs.
func (_u *SkillUpdate) RemoveTeamSkillIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.RemoveTeamSkillIDs(ids...)
	return _u
}

// RemoveTeamSkills removes "team_skills" edges to TeamSkill entities.
func (_u *SkillUpdate) RemoveTeamSkills(v ...*TeamSkill) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamSkillIDs(ids...)
}

// ClearTeamGroupSkills clears all "team_group_skills" edges to the TeamGroupSkill entity.
func (_u *SkillUpdate) ClearTeamGroupSkills() *SkillUpdate {
	_u.mutation.ClearTeamGroupSkills()
	return _u
}

// RemoveTeamGroupSkillIDs removes the "team_group_skills" edge to TeamGroupSkill entities by IDs.
func (_u *SkillUpdate) RemoveTeamGroupSkillIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.RemoveTeamGroupSkillIDs(ids...)
	return _u
}

// RemoveTeamGroupSkills removes "team_group_skills" edges to TeamGroupSkill entities.
func (_u *SkillUpdate) RemoveTeamGroupSkills(v ...*TeamGroupSkill) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamGroupSkillIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if skill.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized skill.UpdateDefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := skill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`db: validator failed for field "Skill.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`db: validator failed for field "Skill.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := skill.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`db: validator failed for field "Skill.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceLabel(); ok {
		if err := skill.SourceLabelValidator(v); err != nil {
			return &ValidationError{Name: "source_label", err: fmt.Errorf(`db: validator failed for field "Skill.source_label": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "Skill.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skill.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(skill.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(skill.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(skill.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageObjectKey(); ok {
		_spec.SetField(skill.FieldPackageObjectKey, field.TypeString, value)
	}
	if _u.mutation.PackageObjectKeyCleared() {
		_spec.ClearField(skill.FieldPackageObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.PackageURL(); ok {
		_spec.SetField(skill.FieldPackageURL, field.TypeString, value)
	}
	if _u.mutation.PackageURLCleared() {
		_spec.ClearField(skill.FieldPackageURL, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(skill.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(skill.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillMdPath(); ok {
		_spec.SetField(skill.FieldSkillMdPath, field.TypeString, value)
	}
	if _u.mutation.SkillMdPathCleared() {
		_spec.ClearField(skill.FieldSkillMdPath, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamSkillsIDs(); len(nodes) > 0 && !_u.mutation.TeamSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamGroupSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamGroupSkillsIDs(); len(nodes) > 0 && !_u.mutation.TeamGroupSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamGroupSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SkillUpdateOne) SetDeletedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableDeletedAt(v *time.Time) *SkillUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SkillUpdateOne) ClearDeletedAt() *SkillUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SkillUpdateOne) SetUserID(v uuid.UUID) *SkillUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableUserID(v *uuid.UUID) *SkillUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SkillUpdateOne) SetDescription(v string) *SkillUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableDescription(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *SkillUpdateOne) SetTags(v []string) *SkillUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *SkillUpdateOne) AppendTags(v []string) *SkillUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *SkillUpdateOne) ClearTags() *SkillUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdateOne) SetContent(v string) *SkillUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableContent(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetPackageObjectKey sets the "package_object_key" field.
func (_u *SkillUpdateOne) SetPackageObjectKey(v string) *SkillUpdateOne {
	_u.mutation.SetPackageObjectKey(v)
	return _u
}

// SetNillablePackageObjectKey sets the "package_object_key" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillablePackageObjectKey(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetPackageObjectKey(*v)
	}
	return _u
}

// ClearPackageObjectKey clears the value of the "package_object_key" field.
func (_u *SkillUpdateOne) ClearPackageObjectKey() *SkillUpdateOne {
	_u.mutation.ClearPackageObjectKey()
	return _u
}

// SetPackageURL sets the "package_url" field.
func (_u *SkillUpdateOne) SetPackageURL(v string) *SkillUpdateOne {
	_u.mutation.SetPackageURL(v)
	return _u
}

// SetNillablePackageURL sets the "package_url" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillablePackageURL(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetPackageURL(*v)
	}
	return _u
}

// ClearPackageURL clears the value of the "package_url" field.
func (_u *SkillUpdateOne) ClearPackageURL() *SkillUpdateOne {
	_u.mutation.ClearPackageURL()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SkillUpdateOne) SetSourceType(v string) *SkillUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableSourceType(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceLabel sets the "source_label" field.
func (_u *SkillUpdateOne) SetSourceLabel(v string) *SkillUpdateOne {
	_u.mutation.SetSourceLabel(v)
	return _u
}

// SetNillableSourceLabel sets the "source_label" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableSourceLabel(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetSourceLabel(*v)
	}
	return _u
}

// SetSkillMdPath sets the "skill_md_path" field.
func (_u *SkillUpdateOne) SetSkillMdPath(v string) *SkillUpdateOne {
	_u.mutation.SetSkillMdPath(v)
	return _u
}

// SetNillableSkillMdPath sets the "skill_md_path" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableSkillMdPath(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetSkillMdPath(*v)
	}
	return _u
}

// ClearSkillMdPath clears the value of the "skill_md_path" field.
func (_u *SkillUpdateOne) ClearSkillMdPath() *SkillUpdateOne {
	_u.mutation.ClearSkillMdPath()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillUpdateOne) SetCreatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCreatedAt(v *time.Time) *SkillUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdateOne) SetUpdatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SkillUpdateOne) SetUser(v *User) *SkillUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *SkillUpdateOne) AddTeamIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *SkillUpdateOne) AddTeams(v ...*Team) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the TeamGroup entity by IDs.
func (_u *SkillUpdateOne) AddGroupIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the TeamGroup entity.
func (_u *SkillUpdateOne) AddGroups(v ...*TeamGroup) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddTeamSkillIDs adds the "team_skills" edge to the TeamSkill entity by IDs.
func (_u *SkillUpdateOne) AddTeamSkillIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.AddTeamSkillIDs(ids...)
	return _u
}

// AddTeamSkills adds the "team_skills" edges to the TeamSkill entity.
func (_u *SkillUpdateOne) AddTeamSkills(v ...*TeamSkill) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamSkillIDs(ids...)
}

// AddTeamGroupSkillIDs adds the "team_group_skills" edge to the TeamGroupSkill entity by IDs.
func (_u *SkillUpdateOne) AddTeamGroupSkillIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.AddTeamGroupSkillIDs(ids...)
	return _u
}

// AddTeamGroupSkills adds the "team_group_skills" edges to the TeamGroupSkill entity.
func (_u *SkillUpdateOne) AddTeamGroupSkills(v ...*TeamGroupSkill) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamGroupSkillIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SkillUpdateOne) ClearUser() *SkillUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *SkillUpdateOne) ClearTeams() *SkillUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *SkillUpdateOne) RemoveTeamIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *SkillUpdateOne) RemoveTeams(v ...*Team) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearGroups clears all "groups" edges to the TeamGroup entity.
func (_u *SkillUpdateOne) ClearGroups() *SkillUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to TeamGroup entities by IDs.
func (_u *SkillUpdateOne) RemoveGroupIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to TeamGroup entities.
func (_u *SkillUpdateOne) RemoveGroups(v ...*TeamGroup) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearTeamSkills clears all "team_skills" edges to the TeamSkill entity.
func (_u *SkillUpdateOne) ClearTeamSkills() *SkillUpdateOne {
	_u.mutation.ClearTeamSkills()
	return _u
}

// RemoveTeamSkillIDs removes the "team_skills" edge to TeamSkill entities by IDs.
func (_u *SkillUpdateOne) RemoveTeamSkillIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.RemoveTeamSkillIDs(ids...)
	return _u
}

// RemoveTeamSkills removes "team_skills" edges to TeamSkill entities.
func (_u *SkillUpdateOne) RemoveTeamSkills(v ...*TeamSkill) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamSkillIDs(ids...)
}

// ClearTeamGroupSkills clears all "team_group_skills" edges to the TeamGroupSkill entity.
func (_u *SkillUpdateOne) ClearTeamGroupSkills() *SkillUpdateOne {
	_u.mutation.ClearTeamGroupSkills()
	return _u
}

// RemoveTeamGroupSkillIDs removes the "team_group_skills" edge to TeamGroupSkill entities by IDs.
func (_u *SkillUpdateOne) RemoveTeamGroupSkillIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.RemoveTeamGroupSkillIDs(ids...)
	return _u
}

// RemoveTeamGroupSkills removes "team_group_skills" edges to TeamGroupSkill entities.
func (_u *SkillUpdateOne) RemoveTeamGroupSkills(v ...*TeamGroupSkill) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamGroupSkillIDs(ids...)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if skill.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized skill.UpdateDefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := skill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`db: validator failed for field "Skill.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`db: validator failed for field "Skill.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := skill.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`db: validator failed for field "Skill.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceLabel(); ok {
		if err := skill.SourceLabelValidator(v); err != nil {
			return &ValidationError{Name: "source_label", err: fmt.Errorf(`db: validator failed for field "Skill.source_label": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "Skill.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(skill.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(skill.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(skill.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, skill.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(skill.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.PackageObjectKey(); ok {
		_spec.SetField(skill.FieldPackageObjectKey, field.TypeString, value)
	}
	if _u.mutation.PackageObjectKeyCleared() {
		_spec.ClearField(skill.FieldPackageObjectKey, field.TypeString)
	}
	if value, ok := _u.mutation.PackageURL(); ok {
		_spec.SetField(skill.FieldPackageURL, field.TypeString, value)
	}
	if _u.mutation.PackageURLCleared() {
		_spec.ClearField(skill.FieldPackageURL, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(skill.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceLabel(); ok {
		_spec.SetField(skill.FieldSourceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkillMdPath(); ok {
		_spec.SetField(skill.FieldSkillMdPath, field.TypeString, value)
	}
	if _u.mutation.SkillMdPathCleared() {
		_spec.ClearField(skill.FieldSkillMdPath, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.UserTable,
			Columns: []string{skill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.TeamsTable,
			Columns: skill.TeamsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamSkillCreate{config: _u.config, mutation: newTeamSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   skill.GroupsTable,
			Columns: skill.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TeamGroupSkillCreate{config: _u.config, mutation: newTeamGroupSkillMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamSkillsIDs(); len(nodes) > 0 && !_u.mutation.TeamSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamSkillsTable,
			Columns: []string{skill.TeamSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamGroupSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamGroupSkillsIDs(); len(nodes) > 0 && !_u.mutation.TeamGroupSkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamGroupSkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   skill.TeamGroupSkillsTable,
			Columns: []string{skill.TeamGroupSkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
