// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/user"
	"github.com/google/uuid"
)

// Skill is the model entity for the Skill schema.
type Skill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// PackageObjectKey holds the value of the "package_object_key" field.
	PackageObjectKey string `json:"package_object_key,omitempty"`
	// PackageURL holds the value of the "package_url" field.
	PackageURL string `json:"package_url,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceLabel holds the value of the "source_label" field.
	SourceLabel string `json:"source_label,omitempty"`
	// SkillMdPath holds the value of the "skill_md_path" field.
	SkillMdPath string `json:"skill_md_path,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SkillQuery when eager-loading is set.
	Edges        SkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SkillEdges holds the relations/edges for other nodes in the graph.
type SkillEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Teams holds the value of the teams edge.
	Teams []*Team `json:"teams,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*TeamGroup `json:"groups,omitempty"`
	// TeamSkills holds the value of the team_skills edge.
	TeamSkills []*TeamSkill `json:"team_skills,omitempty"`
	// TeamGroupSkills holds the value of the team_group_skills edge.
	TeamGroupSkills []*TeamGroupSkill `json:"team_group_skills,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SkillEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TeamsOrErr returns the Teams value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) TeamsOrErr() ([]*Team, error) {
	if e.loadedTypes[1] {
		return e.Teams, nil
	}
	return nil, &NotLoadedError{edge: "teams"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) GroupsOrErr() ([]*TeamGroup, error) {
	if e.loadedTypes[2] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// TeamSkillsOrErr returns the TeamSkills value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) TeamSkillsOrErr() ([]*TeamSkill, error) {
	if e.loadedTypes[3] {
		return e.TeamSkills, nil
	}
	return nil, &NotLoadedError{edge: "team_skills"}
}

// TeamGroupSkillsOrErr returns the TeamGroupSkills value or an error if the edge
// was not loaded in eager-loading.
func (e SkillEdges) TeamGroupSkillsOrErr() ([]*TeamGroupSkill, error) {
	if e.loadedTypes[4] {
		return e.TeamGroupSkills, nil
	}
	return nil, &NotLoadedError{edge: "team_group_skills"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Skill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case skill.FieldTags:
			values[i] = new([]byte)
		case skill.FieldName, skill.FieldDescription, skill.FieldContent, skill.FieldPackageObjectKey, skill.FieldPackageURL, skill.FieldSourceType, skill.FieldSourceLabel, skill.FieldSkillMdPath:
			values[i] = new(sql.NullString)
		case skill.FieldDeletedAt, skill.FieldCreatedAt, skill.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case skill.FieldID, skill.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Skill fields.
func (_m *Skill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case skill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case skill.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case skill.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case skill.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case skill.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case skill.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case skill.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case skill.FieldPackageObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_object_key", values[i])
			} else if value.Valid {
				_m.PackageObjectKey = value.String
			}
		case skill.FieldPackageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_url", values[i])
			} else if value.Valid {
				_m.PackageURL = value.String
			}
		case skill.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case skill.FieldSourceLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_label", values[i])
			} else if value.Valid {
				_m.SourceLabel = value.String
			}
		case skill.FieldSkillMdPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skill_md_path", values[i])
			} else if value.Valid {
				_m.SkillMdPath = value.String
			}
		case skill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case skill.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Skill.
// This includes values selected through modifiers, order, etc.
func (_m *Skill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Skill entity.
func (_m *Skill) QueryUser() *UserQuery {
	return NewSkillClient(_m.config).QueryUser(_m)
}

// QueryTeams queries the "teams" edge of the Skill entity.
func (_m *Skill) QueryTeams() *TeamQuery {
	return NewSkillClient(_m.config).QueryTeams(_m)
}

// QueryGroups queries the "groups" edge of the Skill entity.
func (_m *Skill) QueryGroups() *TeamGroupQuery {
	return NewSkillClient(_m.config).QueryGroups(_m)
}

// QueryTeamSkills queries the "team_skills" edge of the Skill entity.
func (_m *Skill) QueryTeamSkills() *TeamSkillQuery {
	return NewSkillClient(_m.config).QueryTeamSkills(_m)
}

// QueryTeamGroupSkills queries the "team_group_skills" edge of the Skill entity.
func (_m *Skill) QueryTeamGroupSkills() *TeamGroupSkillQuery {
	return NewSkillClient(_m.config).QueryTeamGroupSkills(_m)
}

// Update returns a builder for updating this Skill.
// Note that you need to call Skill.Unwrap() before calling this method if this Skill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Skill) Update() *SkillUpdateOne {
	return NewSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Skill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Skill) Unwrap() *Skill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: Skill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Skill) String() string {
	var builder strings.Builder
	builder.WriteString("Skill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("package_object_key=")
	builder.WriteString(_m.PackageObjectKey)
	builder.WriteString(", ")
	builder.WriteString("package_url=")
	builder.WriteString(_m.PackageURL)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_label=")
	builder.WriteString(_m.SourceLabel)
	builder.WriteString(", ")
	builder.WriteString("skill_md_path=")
	builder.WriteString(_m.SkillMdPath)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Skills is a parsable slice of Skill.
type Skills []*Skill
