// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/MonkeyCode/backend/db/predicate"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/team"
	"github.com/ghshhf/MonkeyCode/backend/db/teamskill"
	"github.com/google/uuid"
)

// TeamSkillUpdate is the builder for updating TeamSkill entities.
type TeamSkillUpdate struct {
	config
	hooks     []Hook
	mutation  *TeamSkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TeamSkillUpdate builder.
func (_u *TeamSkillUpdate) Where(ps ...predicate.TeamSkill) *TeamSkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamSkillUpdate) SetTeamID(v uuid.UUID) *TeamSkillUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamSkillUpdate) SetNillableTeamID(v *uuid.UUID) *TeamSkillUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TeamSkillUpdate) SetSkillID(v uuid.UUID) *TeamSkillUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TeamSkillUpdate) SetNillableSkillID(v *uuid.UUID) *TeamSkillUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamSkillUpdate) SetCreatedAt(v time.Time) *TeamSkillUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamSkillUpdate) SetNillableCreatedAt(v *time.Time) *TeamSkillUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamSkillUpdate) SetTeam(v *Team) *TeamSkillUpdate {
	return _u.SetTeamID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TeamSkillUpdate) SetSkill(v *Skill) *TeamSkillUpdate {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the TeamSkillMutation object of the builder.
func (_u *TeamSkillUpdate) Mutation() *TeamSkillMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamSkillUpdate) ClearTeam() *TeamSkillUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TeamSkillUpdate) ClearSkill() *TeamSkillUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamSkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamSkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamSkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamSkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamSkillUpdate) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamSkill.team"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamSkill.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamSkillUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamSkillUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamSkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamskill.Table, teamskill.Columns, sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamskill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.TeamTable,
			Columns: []string{teamskill.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.TeamTable,
			Columns: []string{teamskill.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.SkillTable,
			Columns: []string{teamskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.SkillTable,
			Columns: []string{teamskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamSkillUpdateOne is the builder for updating a single TeamSkill entity.
type TeamSkillUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TeamSkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTeamID sets the "team_id" field.
func (_u *TeamSkillUpdateOne) SetTeamID(v uuid.UUID) *TeamSkillUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamSkillUpdateOne) SetNillableTeamID(v *uuid.UUID) *TeamSkillUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TeamSkillUpdateOne) SetSkillID(v uuid.UUID) *TeamSkillUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TeamSkillUpdateOne) SetNillableSkillID(v *uuid.UUID) *TeamSkillUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamSkillUpdateOne) SetCreatedAt(v time.Time) *TeamSkillUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamSkillUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamSkillUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamSkillUpdateOne) SetTeam(v *Team) *TeamSkillUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TeamSkillUpdateOne) SetSkill(v *Skill) *TeamSkillUpdateOne {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the TeamSkillMutation object of the builder.
func (_u *TeamSkillUpdateOne) Mutation() *TeamSkillMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamSkillUpdateOne) ClearTeam() *TeamSkillUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TeamSkillUpdateOne) ClearSkill() *TeamSkillUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// Where appends a list predicates to the TeamSkillUpdate builder.
func (_u *TeamSkillUpdateOne) Where(ps ...predicate.TeamSkill) *TeamSkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamSkillUpdateOne) Select(field string, fields ...string) *TeamSkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamSkill entity.
func (_u *TeamSkillUpdateOne) Save(ctx context.Context) (*TeamSkill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamSkillUpdateOne) SaveX(ctx context.Context) *TeamSkill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamSkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamSkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamSkillUpdateOne) check() error {
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamSkill.team"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamSkill.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamSkillUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamSkillUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamSkillUpdateOne) sqlSave(ctx context.Context) (_node *TeamSkill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamskill.Table, teamskill.Columns, sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "TeamSkill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamskill.FieldID)
		for _, f := range fields {
			if !teamskill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != teamskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamskill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.TeamTable,
			Columns: []string{teamskill.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.TeamTable,
			Columns: []string{teamskill.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.SkillTable,
			Columns: []string{teamskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.SkillTable,
			Columns: []string{teamskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TeamSkill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
