// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/MonkeyCode/backend/db/predicate"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/teamgroup"
	"github.com/ghshhf/MonkeyCode/backend/db/teamgroupskill"
	"github.com/google/uuid"
)

// TeamGroupSkillUpdate is the builder for updating TeamGroupSkill entities.
type TeamGroupSkillUpdate struct {
	config
	hooks     []Hook
	mutation  *TeamGroupSkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TeamGroupSkillUpdate builder.
func (_u *TeamGroupSkillUpdate) Where(ps ...predicate.TeamGroupSkill) *TeamGroupSkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *TeamGroupSkillUpdate) SetGroupID(v uuid.UUID) *TeamGroupSkillUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TeamGroupSkillUpdate) SetNillableGroupID(v *uuid.UUID) *TeamGroupSkillUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TeamGroupSkillUpdate) SetSkillID(v uuid.UUID) *TeamGroupSkillUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TeamGroupSkillUpdate) SetNillableSkillID(v *uuid.UUID) *TeamGroupSkillUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamGroupSkillUpdate) SetCreatedAt(v time.Time) *TeamGroupSkillUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamGroupSkillUpdate) SetNillableCreatedAt(v *time.Time) *TeamGroupSkillUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the TeamGroup entity.
func (_u *TeamGroupSkillUpdate) SetGroup(v *TeamGroup) *TeamGroupSkillUpdate {
	return _u.SetGroupID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TeamGroupSkillUpdate) SetSkill(v *Skill) *TeamGroupSkillUpdate {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the TeamGroupSkillMutation object of the builder.
func (_u *TeamGroupSkillUpdate) Mutation() *TeamGroupSkillMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the TeamGroup entity.
func (_u *TeamGroupSkillUpdate) ClearGroup() *TeamGroupSkillUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TeamGroupSkillUpdate) ClearSkill() *TeamGroupSkillUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamGroupSkillUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamGroupSkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamGroupSkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamGroupSkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamGroupSkillUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamGroupSkill.group"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamGroupSkill.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamGroupSkillUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamGroupSkillUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamGroupSkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamgroupskill.Table, teamgroupskill.Columns, sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamgroupskill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.GroupTable,
			Columns: []string{teamgroupskill.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.GroupTable,
			Columns: []string{teamgroupskill.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.SkillTable,
			Columns: []string{teamgroupskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.SkillTable,
			Columns: []string{teamgroupskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamgroupskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamGroupSkillUpdateOne is the builder for updating a single TeamGroupSkill entity.
type TeamGroupSkillUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TeamGroupSkillMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetGroupID sets the "group_id" field.
func (_u *TeamGroupSkillUpdateOne) SetGroupID(v uuid.UUID) *TeamGroupSkillUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *TeamGroupSkillUpdateOne) SetNillableGroupID(v *uuid.UUID) *TeamGroupSkillUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *TeamGroupSkillUpdateOne) SetSkillID(v uuid.UUID) *TeamGroupSkillUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *TeamGroupSkillUpdateOne) SetNillableSkillID(v *uuid.UUID) *TeamGroupSkillUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TeamGroupSkillUpdateOne) SetCreatedAt(v time.Time) *TeamGroupSkillUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TeamGroupSkillUpdateOne) SetNillableCreatedAt(v *time.Time) *TeamGroupSkillUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the TeamGroup entity.
func (_u *TeamGroupSkillUpdateOne) SetGroup(v *TeamGroup) *TeamGroupSkillUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *TeamGroupSkillUpdateOne) SetSkill(v *Skill) *TeamGroupSkillUpdateOne {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the TeamGroupSkillMutation object of the builder.
func (_u *TeamGroupSkillUpdateOne) Mutation() *TeamGroupSkillMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the TeamGroup entity.
func (_u *TeamGroupSkillUpdateOne) ClearGroup() *TeamGroupSkillUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *TeamGroupSkillUpdateOne) ClearSkill() *TeamGroupSkillUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// Where appends a list predicates to the TeamGroupSkillUpdate builder.
func (_u *TeamGroupSkillUpdateOne) Where(ps ...predicate.TeamGroupSkill) *TeamGroupSkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamGroupSkillUpdateOne) Select(field string, fields ...string) *TeamGroupSkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamGroupSkill entity.
func (_u *TeamGroupSkillUpdateOne) Save(ctx context.Context) (*TeamGroupSkill, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamGroupSkillUpdateOne) SaveX(ctx context.Context) *TeamGroupSkill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamGroupSkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamGroupSkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamGroupSkillUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamGroupSkill.group"`)
	}
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "TeamGroupSkill.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TeamGroupSkillUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TeamGroupSkillUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TeamGroupSkillUpdateOne) sqlSave(ctx context.Context) (_node *TeamGroupSkill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamgroupskill.Table, teamgroupskill.Columns, sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "TeamGroupSkill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamgroupskill.FieldID)
		for _, f := range fields {
			if !teamgroupskill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != teamgroupskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(teamgroupskill.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.GroupTable,
			Columns: []string{teamgroupskill.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.GroupTable,
			Columns: []string{teamgroupskill.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.SkillTable,
			Columns: []string{teamgroupskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.SkillTable,
			Columns: []string{teamgroupskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TeamGroupSkill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamgroupskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
