// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/quantum-platform/backend/db/predicate"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroupskill"
)

// TeamGroupSkillDelete is the builder for deleting a TeamGroupSkill entity.
type TeamGroupSkillDelete struct {
	config
	hooks    []Hook
	mutation *TeamGroupSkillMutation
}

// Where appends a list predicates to the TeamGroupSkillDelete builder.
func (_d *TeamGroupSkillDelete) Where(ps ...predicate.TeamGroupSkill) *TeamGroupSkillDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamGroupSkillDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamGroupSkillDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamGroupSkillDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamgroupskill.Table, sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamGroupSkillDeleteOne is the builder for deleting a single TeamGroupSkill entity.
type TeamGroupSkillDeleteOne struct {
	_d *TeamGroupSkillDelete
}

// Where appends a list predicates to the TeamGroupSkillDelete builder.
func (_d *TeamGroupSkillDeleteOne) Where(ps ...predicate.TeamGroupSkill) *TeamGroupSkillDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamGroupSkillDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamgroupskill.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamGroupSkillDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
