// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/quantum-platform/backend/db/skill"
	"github.com/ghshhf/quantum-platform/backend/db/team"
	"github.com/ghshhf/quantum-platform/backend/db/teamskill"
	"github.com/google/uuid"
)

// TeamSkillCreate is the builder for creating a TeamSkill entity.
type TeamSkillCreate struct {
	config
	mutation *TeamSkillMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTeamID sets the "team_id" field.
func (_c *TeamSkillCreate) SetTeamID(v uuid.UUID) *TeamSkillCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *TeamSkillCreate) SetSkillID(v uuid.UUID) *TeamSkillCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamSkillCreate) SetCreatedAt(v time.Time) *TeamSkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamSkillCreate) SetNillableCreatedAt(v *time.Time) *TeamSkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamSkillCreate) SetID(v uuid.UUID) *TeamSkillCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamSkillCreate) SetTeam(v *Team) *TeamSkillCreate {
	return _c.SetTeamID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_c *TeamSkillCreate) SetSkill(v *Skill) *TeamSkillCreate {
	return _c.SetSkillID(v.ID)
}

// Mutation returns the TeamSkillMutation object of the builder.
func (_c *TeamSkillCreate) Mutation() *TeamSkillMutation {
	return _c.mutation
}

// Save creates the TeamSkill in the database.
func (_c *TeamSkillCreate) Save(ctx context.Context) (*TeamSkill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamSkillCreate) SaveX(ctx context.Context) *TeamSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamSkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamSkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamSkillCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamskill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamSkillCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`db: missing required field "TeamSkill.team_id"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`db: missing required field "TeamSkill.skill_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "TeamSkill.created_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`db: missing required edge "TeamSkill.team"`)}
	}
	if len(_c.mutation.SkillIDs()) == 0 {
		return &ValidationError{Name: "skill", err: errors.New(`db: missing required edge "TeamSkill.skill"`)}
	}
	return nil
}

func (_c *TeamSkillCreate) sqlSave(ctx context.Context) (*TeamSkill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamSkillCreate) createSpec() (*TeamSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamSkill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamskill.Table, sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamskill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.TeamTable,
			Columns: []string{teamskill.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamskill.SkillTable,
			Columns: []string{teamskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkillID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamSkill.Create().
//		SetTeamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamSkillUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamSkillCreate) OnConflict(opts ...sql.ConflictOption) *TeamSkillUpsertOne {
	_c.conflict = opts
	return &TeamSkillUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamSkillCreate) OnConflictColumns(columns ...string) *TeamSkillUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamSkillUpsertOne{
		create: _c,
	}
}

type (
	// TeamSkillUpsertOne is the builder for "upsert"-ing
	//  one TeamSkill node.
	TeamSkillUpsertOne struct {
		create *TeamSkillCreate
	}

	// TeamSkillUpsert is the "OnConflict" setter.
	TeamSkillUpsert struct {
		*sql.UpdateSet
	}
)

// SetTeamID sets the "team_id" field.
func (u *TeamSkillUpsert) SetTeamID(v uuid.UUID) *TeamSkillUpsert {
	u.Set(teamskill.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamSkillUpsert) UpdateTeamID() *TeamSkillUpsert {
	u.SetExcluded(teamskill.FieldTeamID)
	return u
}

// SetSkillID sets the "skill_id" field.
func (u *TeamSkillUpsert) SetSkillID(v uuid.UUID) *TeamSkillUpsert {
	u.Set(teamskill.FieldSkillID, v)
	return u
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamSkillUpsert) UpdateSkillID() *TeamSkillUpsert {
	u.SetExcluded(teamskill.FieldSkillID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamSkillUpsert) SetCreatedAt(v time.Time) *TeamSkillUpsert {
	u.Set(teamskill.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamSkillUpsert) UpdateCreatedAt() *TeamSkillUpsert {
	u.SetExcluded(teamskill.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamskill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamSkillUpsertOne) UpdateNewValues() *TeamSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(teamskill.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamSkillUpsertOne) Ignore() *TeamSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamSkillUpsertOne) DoNothing() *TeamSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamSkillCreate.OnConflict
// documentation for more info.
func (u *TeamSkillUpsertOne) Update(set func(*TeamSkillUpsert)) *TeamSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamSkillUpsertOne) SetTeamID(v uuid.UUID) *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamSkillUpsertOne) UpdateTeamID() *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateTeamID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *TeamSkillUpsertOne) SetSkillID(v uuid.UUID) *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamSkillUpsertOne) UpdateSkillID() *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamSkillUpsertOne) SetCreatedAt(v time.Time) *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamSkillUpsertOne) UpdateCreatedAt() *TeamSkillUpsertOne {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamSkillUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamSkillCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamSkillUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamSkillUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: TeamSkillUpsertOne.ID is not supported by MySQL driver. Use TeamSkillUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamSkillUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamSkillCreateBulk is the builder for creating many TeamSkill entities in bulk.
type TeamSkillCreateBulk struct {
	config
	err      error
	builders []*TeamSkillCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamSkill entities in the database.
func (_c *TeamSkillCreateBulk) Save(ctx context.Context) ([]*TeamSkill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamSkill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamSkillCreateBulk) SaveX(ctx context.Context) []*TeamSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamSkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamSkill.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamSkillUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamSkillCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamSkillUpsertBulk {
	_c.conflict = opts
	return &TeamSkillUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamSkillCreateBulk) OnConflictColumns(columns ...string) *TeamSkillUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamSkillUpsertBulk{
		create: _c,
	}
}

// TeamSkillUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamSkill nodes.
type TeamSkillUpsertBulk struct {
	create *TeamSkillCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamskill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamSkillUpsertBulk) UpdateNewValues() *TeamSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(teamskill.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamSkill.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamSkillUpsertBulk) Ignore() *TeamSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamSkillUpsertBulk) DoNothing() *TeamSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamSkillCreateBulk.OnConflict
// documentation for more info.
func (u *TeamSkillUpsertBulk) Update(set func(*TeamSkillUpsert)) *TeamSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamSkillUpsertBulk) SetTeamID(v uuid.UUID) *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamSkillUpsertBulk) UpdateTeamID() *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateTeamID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *TeamSkillUpsertBulk) SetSkillID(v uuid.UUID) *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamSkillUpsertBulk) UpdateSkillID() *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamSkillUpsertBulk) SetCreatedAt(v time.Time) *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamSkillUpsertBulk) UpdateCreatedAt() *TeamSkillUpsertBulk {
	return u.Update(func(s *TeamSkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamSkillUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the TeamSkillCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamSkillCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamSkillUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
