// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/team"
	"github.com/ghshhf/MonkeyCode/backend/db/teamskill"
	"github.com/google/uuid"
)

// TeamSkill is the model entity for the TeamSkill schema.
type TeamSkill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID uuid.UUID `json:"team_id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID uuid.UUID `json:"skill_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamSkillQuery when eager-loading is set.
	Edges        TeamSkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamSkillEdges holds the relations/edges for other nodes in the graph.
type TeamSkillEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// Skill holds the value of the skill edge.
	Skill *Skill `json:"skill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamSkillEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamSkillEdges) SkillOrErr() (*Skill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamSkill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamskill.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case teamskill.FieldID, teamskill.FieldTeamID, teamskill.FieldSkillID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamSkill fields.
func (_m *TeamSkill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamskill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teamskill.FieldTeamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value != nil {
				_m.TeamID = *value
			}
		case teamskill.FieldSkillID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value != nil {
				_m.SkillID = *value
			}
		case teamskill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamSkill.
// This includes values selected through modifiers, order, etc.
func (_m *TeamSkill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamSkill entity.
func (_m *TeamSkill) QueryTeam() *TeamQuery {
	return NewTeamSkillClient(_m.config).QueryTeam(_m)
}

// QuerySkill queries the "skill" edge of the TeamSkill entity.
func (_m *TeamSkill) QuerySkill() *SkillQuery {
	return NewTeamSkillClient(_m.config).QuerySkill(_m)
}

// Update returns a builder for updating this TeamSkill.
// Note that you need to call TeamSkill.Unwrap() before calling this method if this TeamSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamSkill) Update() *TeamSkillUpdateOne {
	return NewTeamSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamSkill) Unwrap() *TeamSkill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: TeamSkill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamSkill) String() string {
	var builder strings.Builder
	builder.WriteString("TeamSkill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamSkills is a parsable slice of TeamSkill.
type TeamSkills []*TeamSkill
