// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ghshhf/quantum-platform/backend/db/skill"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroup"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroupskill"
	"github.com/google/uuid"
)

// TeamGroupSkill is the model entity for the TeamGroupSkill schema.
type TeamGroupSkill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// SkillID holds the value of the "skill_id" field.
	SkillID uuid.UUID `json:"skill_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamGroupSkillQuery when eager-loading is set.
	Edges        TeamGroupSkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamGroupSkillEdges holds the relations/edges for other nodes in the graph.
type TeamGroupSkillEdges struct {
	// Group holds the value of the group edge.
	Group *TeamGroup `json:"group,omitempty"`
	// Skill holds the value of the skill edge.
	Skill *Skill `json:"skill,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamGroupSkillEdges) GroupOrErr() (*TeamGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: teamgroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// SkillOrErr returns the Skill value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamGroupSkillEdges) SkillOrErr() (*Skill, error) {
	if e.Skill != nil {
		return e.Skill, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: skill.Label}
	}
	return nil, &NotLoadedError{edge: "skill"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamGroupSkill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamgroupskill.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case teamgroupskill.FieldID, teamgroupskill.FieldGroupID, teamgroupskill.FieldSkillID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamGroupSkill fields.
func (_m *TeamGroupSkill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamgroupskill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teamgroupskill.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case teamgroupskill.FieldSkillID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field skill_id", values[i])
			} else if value != nil {
				_m.SkillID = *value
			}
		case teamgroupskill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamGroupSkill.
// This includes values selected through modifiers, order, etc.
func (_m *TeamGroupSkill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the TeamGroupSkill entity.
func (_m *TeamGroupSkill) QueryGroup() *TeamGroupQuery {
	return NewTeamGroupSkillClient(_m.config).QueryGroup(_m)
}

// QuerySkill queries the "skill" edge of the TeamGroupSkill entity.
func (_m *TeamGroupSkill) QuerySkill() *SkillQuery {
	return NewTeamGroupSkillClient(_m.config).QuerySkill(_m)
}

// Update returns a builder for updating this TeamGroupSkill.
// Note that you need to call TeamGroupSkill.Unwrap() before calling this method if this TeamGroupSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamGroupSkill) Update() *TeamGroupSkillUpdateOne {
	return NewTeamGroupSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamGroupSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamGroupSkill) Unwrap() *TeamGroupSkill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: TeamGroupSkill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamGroupSkill) String() string {
	var builder strings.Builder
	builder.WriteString("TeamGroupSkill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("skill_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkillID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamGroupSkills is a parsable slice of TeamGroupSkill.
type TeamGroupSkills []*TeamGroupSkill
