// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/MonkeyCode/backend/db/predicate"
	"github.com/ghshhf/MonkeyCode/backend/db/teamskill"
)

// TeamSkillDelete is the builder for deleting a TeamSkill entity.
type TeamSkillDelete struct {
	config
	hooks    []Hook
	mutation *TeamSkillMutation
}

// Where appends a list predicates to the TeamSkillDelete builder.
func (_d *TeamSkillDelete) Where(ps ...predicate.TeamSkill) *TeamSkillDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamSkillDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamSkillDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamSkillDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamskill.Table, sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamSkillDeleteOne is the builder for deleting a single TeamSkill entity.
type TeamSkillDeleteOne struct {
	_d *TeamSkillDelete
}

// Where appends a list predicates to the TeamSkillDelete builder.
func (_d *TeamSkillDeleteOne) Where(ps ...predicate.TeamSkill) *TeamSkillDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamSkillDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamskill.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamSkillDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
