// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/MonkeyCode/backend/db/predicate"
	"github.com/ghshhf/MonkeyCode/backend/db/skill"
	"github.com/ghshhf/MonkeyCode/backend/db/team"
	"github.com/ghshhf/MonkeyCode/backend/db/teamskill"
	"github.com/google/uuid"
)

// TeamSkillQuery is the builder for querying TeamSkill entities.
type TeamSkillQuery struct {
	config
	ctx        *QueryContext
	order      []teamskill.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamSkill
	withTeam   *TeamQuery
	withSkill  *SkillQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamSkillQuery builder.
func (_q *TeamSkillQuery) Where(ps ...predicate.TeamSkill) *TeamSkillQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TeamSkillQuery) Limit(limit int) *TeamSkillQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TeamSkillQuery) Offset(offset int) *TeamSkillQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TeamSkillQuery) Unique(unique bool) *TeamSkillQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TeamSkillQuery) Order(o ...teamskill.OrderOption) *TeamSkillQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTeam chains the current query on the "team" edge.
func (_q *TeamSkillQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamskill.Table, teamskill.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamskill.TeamTable, teamskill.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySkill chains the current query on the "skill" edge.
func (_q *TeamSkillQuery) QuerySkill() *SkillQuery {
	query := (&SkillClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamskill.Table, teamskill.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamskill.SkillTable, teamskill.SkillColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamSkill entity from the query.
// Returns a *NotFoundError when no TeamSkill was found.
func (_q *TeamSkillQuery) First(ctx context.Context) (*TeamSkill, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamskill.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TeamSkillQuery) FirstX(ctx context.Context) *TeamSkill {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamSkill ID from the query.
// Returns a *NotFoundError when no TeamSkill ID was found.
func (_q *TeamSkillQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamskill.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TeamSkillQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamSkill entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamSkill entity is found.
// Returns a *NotFoundError when no TeamSkill entities are found.
func (_q *TeamSkillQuery) Only(ctx context.Context) (*TeamSkill, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamskill.Label}
	default:
		return nil, &NotSingularError{teamskill.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TeamSkillQuery) OnlyX(ctx context.Context) *TeamSkill {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamSkill ID in the query.
// Returns a *NotSingularError when more than one TeamSkill ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TeamSkillQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamskill.Label}
	default:
		err = &NotSingularError{teamskill.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TeamSkillQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamSkills.
func (_q *TeamSkillQuery) All(ctx context.Context) ([]*TeamSkill, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamSkill, *TeamSkillQuery]()
	return withInterceptors[[]*TeamSkill](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TeamSkillQuery) AllX(ctx context.Context) []*TeamSkill {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamSkill IDs.
func (_q *TeamSkillQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(teamskill.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TeamSkillQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TeamSkillQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TeamSkillQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TeamSkillQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TeamSkillQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TeamSkillQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamSkillQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TeamSkillQuery) Clone() *TeamSkillQuery {
	if _q == nil {
		return nil
	}
	return &TeamSkillQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]teamskill.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.TeamSkill{}, _q.predicates...),
		withTeam:   _q.withTeam.Clone(),
		withSkill:  _q.withSkill.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TeamSkillQuery) WithTeam(opts ...func(*TeamQuery)) *TeamSkillQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithSkill tells the query-builder to eager-load the nodes that are connected to
// the "skill" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TeamSkillQuery) WithSkill(opts ...func(*SkillQuery)) *TeamSkillQuery {
	query := (&SkillClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSkill = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TeamID uuid.UUID `json:"team_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamSkill.Query().
//		GroupBy(teamskill.FieldTeamID).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *TeamSkillQuery) GroupBy(field string, fields ...string) *TeamSkillGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamSkillGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = teamskill.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TeamID uuid.UUID `json:"team_id,omitempty"`
//	}
//
//	client.TeamSkill.Query().
//		Select(teamskill.FieldTeamID).
//		Scan(ctx, &v)
func (_q *TeamSkillQuery) Select(fields ...string) *TeamSkillSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TeamSkillSelect{TeamSkillQuery: _q}
	sbuild.label = teamskill.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamSkillSelect configured with the given aggregations.
func (_q *TeamSkillQuery) Aggregate(fns ...AggregateFunc) *TeamSkillSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TeamSkillQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !teamskill.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TeamSkillQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamSkill, error) {
	var (
		nodes       = []*TeamSkill{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTeam != nil,
			_q.withSkill != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamSkill).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamSkill{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *TeamSkill, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSkill; query != nil {
		if err := _q.loadSkill(ctx, query, nodes, nil,
			func(n *TeamSkill, e *Skill) { n.Edges.Skill = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TeamSkillQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*TeamSkill, init func(*TeamSkill), assign func(*TeamSkill, *Team)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TeamSkill)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TeamSkillQuery) loadSkill(ctx context.Context, query *SkillQuery, nodes []*TeamSkill, init func(*TeamSkill), assign func(*TeamSkill, *Skill)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TeamSkill)
	for i := range nodes {
		fk := nodes[i].SkillID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(skill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "skill_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TeamSkillQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TeamSkillQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamskill.Table, teamskill.Columns, sqlgraph.NewFieldSpec(teamskill.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamskill.FieldID)
		for i := range fields {
			if fields[i] != teamskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTeam != nil {
			_spec.Node.AddColumnOnce(teamskill.FieldTeamID)
		}
		if _q.withSkill != nil {
			_spec.Node.AddColumnOnce(teamskill.FieldSkillID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TeamSkillQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(teamskill.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = teamskill.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *TeamSkillQuery) ForUpdate(opts ...sql.LockOption) *TeamSkillQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *TeamSkillQuery) ForShare(opts ...sql.LockOption) *TeamSkillQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *TeamSkillQuery) Modify(modifiers ...func(s *sql.Selector)) *TeamSkillSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// TeamSkillGroupBy is the group-by builder for TeamSkill entities.
type TeamSkillGroupBy struct {
	selector
	build *TeamSkillQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TeamSkillGroupBy) Aggregate(fns ...AggregateFunc) *TeamSkillGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TeamSkillGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamSkillQuery, *TeamSkillGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TeamSkillGroupBy) sqlScan(ctx context.Context, root *TeamSkillQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamSkillSelect is the builder for selecting fields of TeamSkill entities.
type TeamSkillSelect struct {
	*TeamSkillQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TeamSkillSelect) Aggregate(fns ...AggregateFunc) *TeamSkillSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TeamSkillSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamSkillQuery, *TeamSkillSelect](ctx, _s.TeamSkillQuery, _s, _s.inters, v)
}

func (_s *TeamSkillSelect) sqlScan(ctx context.Context, root *TeamSkillQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *TeamSkillSelect) Modify(modifiers ...func(s *sql.Selector)) *TeamSkillSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
