// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/quantum-platform/backend/db/predicate"
	"github.com/ghshhf/quantum-platform/backend/db/skill"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroup"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroupskill"
	"github.com/google/uuid"
)

// TeamGroupSkillQuery is the builder for querying TeamGroupSkill entities.
type TeamGroupSkillQuery struct {
	config
	ctx        *QueryContext
	order      []teamgroupskill.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamGroupSkill
	withGroup  *TeamGroupQuery
	withSkill  *SkillQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamGroupSkillQuery builder.
func (_q *TeamGroupSkillQuery) Where(ps ...predicate.TeamGroupSkill) *TeamGroupSkillQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TeamGroupSkillQuery) Limit(limit int) *TeamGroupSkillQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TeamGroupSkillQuery) Offset(offset int) *TeamGroupSkillQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TeamGroupSkillQuery) Unique(unique bool) *TeamGroupSkillQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TeamGroupSkillQuery) Order(o ...teamgroupskill.OrderOption) *TeamGroupSkillQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *TeamGroupSkillQuery) QueryGroup() *TeamGroupQuery {
	query := (&TeamGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamgroupskill.Table, teamgroupskill.FieldID, selector),
			sqlgraph.To(teamgroup.Table, teamgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamgroupskill.GroupTable, teamgroupskill.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySkill chains the current query on the "skill" edge.
func (_q *TeamGroupSkillQuery) QuerySkill() *SkillQuery {
	query := (&SkillClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamgroupskill.Table, teamgroupskill.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamgroupskill.SkillTable, teamgroupskill.SkillColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamGroupSkill entity from the query.
// Returns a *NotFoundError when no TeamGroupSkill was found.
func (_q *TeamGroupSkillQuery) First(ctx context.Context) (*TeamGroupSkill, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamgroupskill.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) FirstX(ctx context.Context) *TeamGroupSkill {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamGroupSkill ID from the query.
// Returns a *NotFoundError when no TeamGroupSkill ID was found.
func (_q *TeamGroupSkillQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamgroupskill.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamGroupSkill entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamGroupSkill entity is found.
// Returns a *NotFoundError when no TeamGroupSkill entities are found.
func (_q *TeamGroupSkillQuery) Only(ctx context.Context) (*TeamGroupSkill, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamgroupskill.Label}
	default:
		return nil, &NotSingularError{teamgroupskill.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) OnlyX(ctx context.Context) *TeamGroupSkill {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamGroupSkill ID in the query.
// Returns a *NotSingularError when more than one TeamGroupSkill ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *TeamGroupSkillQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamgroupskill.Label}
	default:
		err = &NotSingularError{teamgroupskill.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamGroupSkills.
func (_q *TeamGroupSkillQuery) All(ctx context.Context) ([]*TeamGroupSkill, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamGroupSkill, *TeamGroupSkillQuery]()
	return withInterceptors[[]*TeamGroupSkill](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) AllX(ctx context.Context) []*TeamGroupSkill {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamGroupSkill IDs.
func (_q *TeamGroupSkillQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(teamgroupskill.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *TeamGroupSkillQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TeamGroupSkillQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TeamGroupSkillQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TeamGroupSkillQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamGroupSkillQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TeamGroupSkillQuery) Clone() *TeamGroupSkillQuery {
	if _q == nil {
		return nil
	}
	return &TeamGroupSkillQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]teamgroupskill.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.TeamGroupSkill{}, _q.predicates...),
		withGroup:  _q.withGroup.Clone(),
		withSkill:  _q.withSkill.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TeamGroupSkillQuery) WithGroup(opts ...func(*TeamGroupQuery)) *TeamGroupSkillQuery {
	query := (&TeamGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithSkill tells the query-builder to eager-load the nodes that are connected to
// the "skill" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TeamGroupSkillQuery) WithSkill(opts ...func(*SkillQuery)) *TeamGroupSkillQuery {
	query := (&SkillClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSkill = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		GroupID uuid.UUID `json:"group_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamGroupSkill.Query().
//		GroupBy(teamgroupskill.FieldGroupID).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *TeamGroupSkillQuery) GroupBy(field string, fields ...string) *TeamGroupSkillGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamGroupSkillGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = teamgroupskill.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		GroupID uuid.UUID `json:"group_id,omitempty"`
//	}
//
//	client.TeamGroupSkill.Query().
//		Select(teamgroupskill.FieldGroupID).
//		Scan(ctx, &v)
func (_q *TeamGroupSkillQuery) Select(fields ...string) *TeamGroupSkillSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TeamGroupSkillSelect{TeamGroupSkillQuery: _q}
	sbuild.label = teamgroupskill.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamGroupSkillSelect configured with the given aggregations.
func (_q *TeamGroupSkillQuery) Aggregate(fns ...AggregateFunc) *TeamGroupSkillSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TeamGroupSkillQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !teamgroupskill.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TeamGroupSkillQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamGroupSkill, error) {
	var (
		nodes       = []*TeamGroupSkill{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGroup != nil,
			_q.withSkill != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamGroupSkill).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamGroupSkill{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *TeamGroupSkill, e *TeamGroup) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSkill; query != nil {
		if err := _q.loadSkill(ctx, query, nodes, nil,
			func(n *TeamGroupSkill, e *Skill) { n.Edges.Skill = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TeamGroupSkillQuery) loadGroup(ctx context.Context, query *TeamGroupQuery, nodes []*TeamGroupSkill, init func(*TeamGroupSkill), assign func(*TeamGroupSkill, *TeamGroup)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TeamGroupSkill)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(teamgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TeamGroupSkillQuery) loadSkill(ctx context.Context, query *SkillQuery, nodes []*TeamGroupSkill, init func(*TeamGroupSkill), assign func(*TeamGroupSkill, *Skill)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TeamGroupSkill)
	for i := range nodes {
		fk := nodes[i].SkillID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(skill.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "skill_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TeamGroupSkillQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TeamGroupSkillQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamgroupskill.Table, teamgroupskill.Columns, sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamgroupskill.FieldID)
		for i := range fields {
			if fields[i] != teamgroupskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(teamgroupskill.FieldGroupID)
		}
		if _q.withSkill != nil {
			_spec.Node.AddColumnOnce(teamgroupskill.FieldSkillID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TeamGroupSkillQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(teamgroupskill.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = teamgroupskill.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *TeamGroupSkillQuery) ForUpdate(opts ...sql.LockOption) *TeamGroupSkillQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *TeamGroupSkillQuery) ForShare(opts ...sql.LockOption) *TeamGroupSkillQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *TeamGroupSkillQuery) Modify(modifiers ...func(s *sql.Selector)) *TeamGroupSkillSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// TeamGroupSkillGroupBy is the group-by builder for TeamGroupSkill entities.
type TeamGroupSkillGroupBy struct {
	selector
	build *TeamGroupSkillQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TeamGroupSkillGroupBy) Aggregate(fns ...AggregateFunc) *TeamGroupSkillGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TeamGroupSkillGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamGroupSkillQuery, *TeamGroupSkillGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TeamGroupSkillGroupBy) sqlScan(ctx context.Context, root *TeamGroupSkillQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamGroupSkillSelect is the builder for selecting fields of TeamGroupSkill entities.
type TeamGroupSkillSelect struct {
	*TeamGroupSkillQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TeamGroupSkillSelect) Aggregate(fns ...AggregateFunc) *TeamGroupSkillSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TeamGroupSkillSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamGroupSkillQuery, *TeamGroupSkillSelect](ctx, _s.TeamGroupSkillQuery, _s, _s.inters, v)
}

func (_s *TeamGroupSkillSelect) sqlScan(ctx context.Context, root *TeamGroupSkillQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *TeamGroupSkillSelect) Modify(modifiers ...func(s *sql.Selector)) *TeamGroupSkillSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
