// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ghshhf/quantum-platform/backend/db/skill"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroup"
	"github.com/ghshhf/quantum-platform/backend/db/teamgroupskill"
	"github.com/google/uuid"
)

// TeamGroupSkillCreate is the builder for creating a TeamGroupSkill entity.
type TeamGroupSkillCreate struct {
	config
	mutation *TeamGroupSkillMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *TeamGroupSkillCreate) SetGroupID(v uuid.UUID) *TeamGroupSkillCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSkillID sets the "skill_id" field.
func (_c *TeamGroupSkillCreate) SetSkillID(v uuid.UUID) *TeamGroupSkillCreate {
	_c.mutation.SetSkillID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamGroupSkillCreate) SetCreatedAt(v time.Time) *TeamGroupSkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamGroupSkillCreate) SetNillableCreatedAt(v *time.Time) *TeamGroupSkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamGroupSkillCreate) SetID(v uuid.UUID) *TeamGroupSkillCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the TeamGroup entity.
func (_c *TeamGroupSkillCreate) SetGroup(v *TeamGroup) *TeamGroupSkillCreate {
	return _c.SetGroupID(v.ID)
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_c *TeamGroupSkillCreate) SetSkill(v *Skill) *TeamGroupSkillCreate {
	return _c.SetSkillID(v.ID)
}

// Mutation returns the TeamGroupSkillMutation object of the builder.
func (_c *TeamGroupSkillCreate) Mutation() *TeamGroupSkillMutation {
	return _c.mutation
}

// Save creates the TeamGroupSkill in the database.
func (_c *TeamGroupSkillCreate) Save(ctx context.Context) (*TeamGroupSkill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamGroupSkillCreate) SaveX(ctx context.Context) *TeamGroupSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamGroupSkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamGroupSkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamGroupSkillCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamgroupskill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamGroupSkillCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`db: missing required field "TeamGroupSkill.group_id"`)}
	}
	if _, ok := _c.mutation.SkillID(); !ok {
		return &ValidationError{Name: "skill_id", err: errors.New(`db: missing required field "TeamGroupSkill.skill_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "TeamGroupSkill.created_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`db: missing required edge "TeamGroupSkill.group"`)}
	}
	if len(_c.mutation.SkillIDs()) == 0 {
		return &ValidationError{Name: "skill", err: errors.New(`db: missing required edge "TeamGroupSkill.skill"`)}
	}
	return nil
}

func (_c *TeamGroupSkillCreate) sqlSave(ctx context.Context) (*TeamGroupSkill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamGroupSkillCreate) createSpec() (*TeamGroupSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamGroupSkill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamgroupskill.Table, sqlgraph.NewFieldSpec(teamgroupskill.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamgroupskill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.GroupTable,
			Columns: []string{teamgroupskill.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamgroupskill.SkillTable,
			Columns: []string{teamgroupskill.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkillID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamGroupSkill.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamGroupSkillUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamGroupSkillCreate) OnConflict(opts ...sql.ConflictOption) *TeamGroupSkillUpsertOne {
	_c.conflict = opts
	return &TeamGroupSkillUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamGroupSkillCreate) OnConflictColumns(columns ...string) *TeamGroupSkillUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamGroupSkillUpsertOne{
		create: _c,
	}
}

type (
	// TeamGroupSkillUpsertOne is the builder for "upsert"-ing
	//  one TeamGroupSkill node.
	TeamGroupSkillUpsertOne struct {
		create *TeamGroupSkillCreate
	}

	// TeamGroupSkillUpsert is the "OnConflict" setter.
	TeamGroupSkillUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *TeamGroupSkillUpsert) SetGroupID(v uuid.UUID) *TeamGroupSkillUpsert {
	u.Set(teamgroupskill.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsert) UpdateGroupID() *TeamGroupSkillUpsert {
	u.SetExcluded(teamgroupskill.FieldGroupID)
	return u
}

// SetSkillID sets the "skill_id" field.
func (u *TeamGroupSkillUpsert) SetSkillID(v uuid.UUID) *TeamGroupSkillUpsert {
	u.Set(teamgroupskill.FieldSkillID, v)
	return u
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsert) UpdateSkillID() *TeamGroupSkillUpsert {
	u.SetExcluded(teamgroupskill.FieldSkillID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamGroupSkillUpsert) SetCreatedAt(v time.Time) *TeamGroupSkillUpsert {
	u.Set(teamgroupskill.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamGroupSkillUpsert) UpdateCreatedAt() *TeamGroupSkillUpsert {
	u.SetExcluded(teamgroupskill.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamgroupskill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamGroupSkillUpsertOne) UpdateNewValues() *TeamGroupSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(teamgroupskill.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamGroupSkillUpsertOne) Ignore() *TeamGroupSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamGroupSkillUpsertOne) DoNothing() *TeamGroupSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamGroupSkillCreate.OnConflict
// documentation for more info.
func (u *TeamGroupSkillUpsertOne) Update(set func(*TeamGroupSkillUpsert)) *TeamGroupSkillUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamGroupSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *TeamGroupSkillUpsertOne) SetGroupID(v uuid.UUID) *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertOne) UpdateGroupID() *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateGroupID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *TeamGroupSkillUpsertOne) SetSkillID(v uuid.UUID) *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertOne) UpdateSkillID() *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamGroupSkillUpsertOne) SetCreatedAt(v time.Time) *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertOne) UpdateCreatedAt() *TeamGroupSkillUpsertOne {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamGroupSkillUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamGroupSkillCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamGroupSkillUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamGroupSkillUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: TeamGroupSkillUpsertOne.ID is not supported by MySQL driver. Use TeamGroupSkillUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamGroupSkillUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamGroupSkillCreateBulk is the builder for creating many TeamGroupSkill entities in bulk.
type TeamGroupSkillCreateBulk struct {
	config
	err      error
	builders []*TeamGroupSkillCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamGroupSkill entities in the database.
func (_c *TeamGroupSkillCreateBulk) Save(ctx context.Context) ([]*TeamGroupSkill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamGroupSkill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamGroupSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamGroupSkillCreateBulk) SaveX(ctx context.Context) []*TeamGroupSkill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamGroupSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamGroupSkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamGroupSkill.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamGroupSkillUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamGroupSkillCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamGroupSkillUpsertBulk {
	_c.conflict = opts
	return &TeamGroupSkillUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamGroupSkillCreateBulk) OnConflictColumns(columns ...string) *TeamGroupSkillUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamGroupSkillUpsertBulk{
		create: _c,
	}
}

// TeamGroupSkillUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamGroupSkill nodes.
type TeamGroupSkillUpsertBulk struct {
	create *TeamGroupSkillCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(teamgroupskill.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TeamGroupSkillUpsertBulk) UpdateNewValues() *TeamGroupSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(teamgroupskill.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamGroupSkill.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamGroupSkillUpsertBulk) Ignore() *TeamGroupSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamGroupSkillUpsertBulk) DoNothing() *TeamGroupSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamGroupSkillCreateBulk.OnConflict
// documentation for more info.
func (u *TeamGroupSkillUpsertBulk) Update(set func(*TeamGroupSkillUpsert)) *TeamGroupSkillUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamGroupSkillUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *TeamGroupSkillUpsertBulk) SetGroupID(v uuid.UUID) *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertBulk) UpdateGroupID() *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateGroupID()
	})
}

// SetSkillID sets the "skill_id" field.
func (u *TeamGroupSkillUpsertBulk) SetSkillID(v uuid.UUID) *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetSkillID(v)
	})
}

// UpdateSkillID sets the "skill_id" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertBulk) UpdateSkillID() *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateSkillID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TeamGroupSkillUpsertBulk) SetCreatedAt(v time.Time) *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TeamGroupSkillUpsertBulk) UpdateCreatedAt() *TeamGroupSkillUpsertBulk {
	return u.Update(func(s *TeamGroupSkillUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *TeamGroupSkillUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the TeamGroupSkillCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for TeamGroupSkillCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamGroupSkillUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
