// Code generated by ent, DO NOT EDIT.

package skill

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the skill type in the database.
	Label = "skill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldPackageObjectKey holds the string denoting the package_object_key field in the database.
	FieldPackageObjectKey = "package_object_key"
	// FieldPackageURL holds the string denoting the package_url field in the database.
	FieldPackageURL = "package_url"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceLabel holds the string denoting the source_label field in the database.
	FieldSourceLabel = "source_label"
	// FieldSkillMdPath holds the string denoting the skill_md_path field in the database.
	FieldSkillMdPath = "skill_md_path"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeTeams holds the string denoting the teams edge name in mutations.
	EdgeTeams = "teams"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeTeamSkills holds the string denoting the team_skills edge name in mutations.
	EdgeTeamSkills = "team_skills"
	// EdgeTeamGroupSkills holds the string denoting the team_group_skills edge name in mutations.
	EdgeTeamGroupSkills = "team_group_skills"
	// Table holds the table name of the skill in the database.
	Table = "skills"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "skills"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// TeamsTable is the table that holds the teams relation/edge. The primary key declared below.
	TeamsTable = "team_skills"
	// TeamsInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamsInverseTable = "teams"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "team_group_skills"
	// GroupsInverseTable is the table name for the TeamGroup entity.
	// It exists in this package in order to avoid circular dependency with the "teamgroup" package.
	GroupsInverseTable = "team_groups"
	// TeamSkillsTable is the table that holds the team_skills relation/edge.
	TeamSkillsTable = "team_skills"
	// TeamSkillsInverseTable is the table name for the TeamSkill entity.
	// It exists in this package in order to avoid circular dependency with the "teamskill" package.
	TeamSkillsInverseTable = "team_skills"
	// TeamSkillsColumn is the table column denoting the team_skills relation/edge.
	TeamSkillsColumn = "skill_id"
	// TeamGroupSkillsTable is the table that holds the team_group_skills relation/edge.
	TeamGroupSkillsTable = "team_group_skills"
	// TeamGroupSkillsInverseTable is the table name for the TeamGroupSkill entity.
	// It exists in this package in order to avoid circular dependency with the "teamgroupskill" package.
	TeamGroupSkillsInverseTable = "team_group_skills"
	// TeamGroupSkillsColumn is the table column denoting the team_group_skills relation/edge.
	TeamGroupSkillsColumn = "skill_id"
)

// Columns holds all SQL columns for skill fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldUserID,
	FieldName,
	FieldDescription,
	FieldTags,
	FieldContent,
	FieldPackageObjectKey,
	FieldPackageURL,
	FieldSourceType,
	FieldSourceLabel,
	FieldSkillMdPath,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// TeamsPrimaryKey and TeamsColumn2 are the table columns denoting the
	// primary key for the teams relation (M2M).
	TeamsPrimaryKey = []string{"team_id", "skill_id"}
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"group_id", "skill_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ghshhf/MonkeyCode/backend/db/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// SourceLabelValidator is a validator for the "source_label" field. It is called by the builders before save.
	SourceLabelValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Skill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByPackageObjectKey orders the results by the package_object_key field.
func ByPackageObjectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageObjectKey, opts...).ToFunc()
}

// ByPackageURL orders the results by the package_url field.
func ByPackageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageURL, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceLabel orders the results by the source_label field.
func BySourceLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceLabel, opts...).ToFunc()
}

// BySkillMdPath orders the results by the skill_md_path field.
func BySkillMdPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkillMdPath, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTeamsCount orders the results by teams count.
func ByTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamsStep(), opts...)
	}
}

// ByTeams orders the results by teams terms.
func ByTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamSkillsCount orders the results by team_skills count.
func ByTeamSkillsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamSkillsStep(), opts...)
	}
}

// ByTeamSkills orders the results by team_skills terms.
func ByTeamSkills(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamSkillsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamGroupSkillsCount orders the results by team_group_skills count.
func ByTeamGroupSkillsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamGroupSkillsStep(), opts...)
	}
}

// ByTeamGroupSkills orders the results by team_group_skills terms.
func ByTeamGroupSkills(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamGroupSkillsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, TeamsTable, TeamsPrimaryKey...),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, GroupsTable, GroupsPrimaryKey...),
	)
}
func newTeamSkillsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamSkillsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TeamSkillsTable, TeamSkillsColumn),
	)
}
func newTeamGroupSkillsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamGroupSkillsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupSkillsTable, TeamGroupSkillsColumn),
	)
}
