// Code generated by ent, DO NOT EDIT.

package skill

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ghshhf/quantum-platform/backend/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDescription, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldContent, v))
}

// PackageObjectKey applies equality check predicate on the "package_object_key" field. It's identical to PackageObjectKeyEQ.
func PackageObjectKey(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPackageObjectKey, v))
}

// PackageURL applies equality check predicate on the "package_url" field. It's identical to PackageURLEQ.
func PackageURL(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPackageURL, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSourceType, v))
}

// SourceLabel applies equality check predicate on the "source_label" field. It's identical to SourceLabelEQ.
func SourceLabel(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSourceLabel, v))
}

// SkillMdPath applies equality check predicate on the "skill_md_path" field. It's identical to SkillMdPathEQ.
func SkillMdPath(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSkillMdPath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldUserID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldDescription, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldTags))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldContent, v))
}

// PackageObjectKeyEQ applies the EQ predicate on the "package_object_key" field.
func PackageObjectKeyEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPackageObjectKey, v))
}

// PackageObjectKeyNEQ applies the NEQ predicate on the "package_object_key" field.
func PackageObjectKeyNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldPackageObjectKey, v))
}

// PackageObjectKeyIn applies the In predicate on the "package_object_key" field.
func PackageObjectKeyIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldPackageObjectKey, vs...))
}

// PackageObjectKeyNotIn applies the NotIn predicate on the "package_object_key" field.
func PackageObjectKeyNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldPackageObjectKey, vs...))
}

// PackageObjectKeyGT applies the GT predicate on the "package_object_key" field.
func PackageObjectKeyGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldPackageObjectKey, v))
}

// PackageObjectKeyGTE applies the GTE predicate on the "package_object_key" field.
func PackageObjectKeyGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldPackageObjectKey, v))
}

// PackageObjectKeyLT applies the LT predicate on the "package_object_key" field.
func PackageObjectKeyLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldPackageObjectKey, v))
}

// PackageObjectKeyLTE applies the LTE predicate on the "package_object_key" field.
func PackageObjectKeyLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldPackageObjectKey, v))
}

// PackageObjectKeyContains applies the Contains predicate on the "package_object_key" field.
func PackageObjectKeyContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldPackageObjectKey, v))
}

// PackageObjectKeyHasPrefix applies the HasPrefix predicate on the "package_object_key" field.
func PackageObjectKeyHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldPackageObjectKey, v))
}

// PackageObjectKeyHasSuffix applies the HasSuffix predicate on the "package_object_key" field.
func PackageObjectKeyHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldPackageObjectKey, v))
}

// PackageObjectKeyIsNil applies the IsNil predicate on the "package_object_key" field.
func PackageObjectKeyIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldPackageObjectKey))
}

// PackageObjectKeyNotNil applies the NotNil predicate on the "package_object_key" field.
func PackageObjectKeyNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldPackageObjectKey))
}

// PackageObjectKeyEqualFold applies the EqualFold predicate on the "package_object_key" field.
func PackageObjectKeyEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldPackageObjectKey, v))
}

// PackageObjectKeyContainsFold applies the ContainsFold predicate on the "package_object_key" field.
func PackageObjectKeyContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldPackageObjectKey, v))
}

// PackageURLEQ applies the EQ predicate on the "package_url" field.
func PackageURLEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldPackageURL, v))
}

// PackageURLNEQ applies the NEQ predicate on the "package_url" field.
func PackageURLNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldPackageURL, v))
}

// PackageURLIn applies the In predicate on the "package_url" field.
func PackageURLIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldPackageURL, vs...))
}

// PackageURLNotIn applies the NotIn predicate on the "package_url" field.
func PackageURLNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldPackageURL, vs...))
}

// PackageURLGT applies the GT predicate on the "package_url" field.
func PackageURLGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldPackageURL, v))
}

// PackageURLGTE applies the GTE predicate on the "package_url" field.
func PackageURLGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldPackageURL, v))
}

// PackageURLLT applies the LT predicate on the "package_url" field.
func PackageURLLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldPackageURL, v))
}

// PackageURLLTE applies the LTE predicate on the "package_url" field.
func PackageURLLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldPackageURL, v))
}

// PackageURLContains applies the Contains predicate on the "package_url" field.
func PackageURLContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldPackageURL, v))
}

// PackageURLHasPrefix applies the HasPrefix predicate on the "package_url" field.
func PackageURLHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldPackageURL, v))
}

// PackageURLHasSuffix applies the HasSuffix predicate on the "package_url" field.
func PackageURLHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldPackageURL, v))
}

// PackageURLIsNil applies the IsNil predicate on the "package_url" field.
func PackageURLIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldPackageURL))
}

// PackageURLNotNil applies the NotNil predicate on the "package_url" field.
func PackageURLNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldPackageURL))
}

// PackageURLEqualFold applies the EqualFold predicate on the "package_url" field.
func PackageURLEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldPackageURL, v))
}

// PackageURLContainsFold applies the ContainsFold predicate on the "package_url" field.
func PackageURLContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldPackageURL, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceLabelEQ applies the EQ predicate on the "source_label" field.
func SourceLabelEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSourceLabel, v))
}

// SourceLabelNEQ applies the NEQ predicate on the "source_label" field.
func SourceLabelNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldSourceLabel, v))
}

// SourceLabelIn applies the In predicate on the "source_label" field.
func SourceLabelIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldSourceLabel, vs...))
}

// SourceLabelNotIn applies the NotIn predicate on the "source_label" field.
func SourceLabelNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldSourceLabel, vs...))
}

// SourceLabelGT applies the GT predicate on the "source_label" field.
func SourceLabelGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldSourceLabel, v))
}

// SourceLabelGTE applies the GTE predicate on the "source_label" field.
func SourceLabelGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldSourceLabel, v))
}

// SourceLabelLT applies the LT predicate on the "source_label" field.
func SourceLabelLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldSourceLabel, v))
}

// SourceLabelLTE applies the LTE predicate on the "source_label" field.
func SourceLabelLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldSourceLabel, v))
}

// SourceLabelContains applies the Contains predicate on the "source_label" field.
func SourceLabelContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldSourceLabel, v))
}

// SourceLabelHasPrefix applies the HasPrefix predicate on the "source_label" field.
func SourceLabelHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldSourceLabel, v))
}

// SourceLabelHasSuffix applies the HasSuffix predicate on the "source_label" field.
func SourceLabelHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldSourceLabel, v))
}

// SourceLabelEqualFold applies the EqualFold predicate on the "source_label" field.
func SourceLabelEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldSourceLabel, v))
}

// SourceLabelContainsFold applies the ContainsFold predicate on the "source_label" field.
func SourceLabelContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldSourceLabel, v))
}

// SkillMdPathEQ applies the EQ predicate on the "skill_md_path" field.
func SkillMdPathEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldSkillMdPath, v))
}

// SkillMdPathNEQ applies the NEQ predicate on the "skill_md_path" field.
func SkillMdPathNEQ(v string) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldSkillMdPath, v))
}

// SkillMdPathIn applies the In predicate on the "skill_md_path" field.
func SkillMdPathIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldSkillMdPath, vs...))
}

// SkillMdPathNotIn applies the NotIn predicate on the "skill_md_path" field.
func SkillMdPathNotIn(vs ...string) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldSkillMdPath, vs...))
}

// SkillMdPathGT applies the GT predicate on the "skill_md_path" field.
func SkillMdPathGT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldSkillMdPath, v))
}

// SkillMdPathGTE applies the GTE predicate on the "skill_md_path" field.
func SkillMdPathGTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldSkillMdPath, v))
}

// SkillMdPathLT applies the LT predicate on the "skill_md_path" field.
func SkillMdPathLT(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldSkillMdPath, v))
}

// SkillMdPathLTE applies the LTE predicate on the "skill_md_path" field.
func SkillMdPathLTE(v string) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldSkillMdPath, v))
}

// SkillMdPathContains applies the Contains predicate on the "skill_md_path" field.
func SkillMdPathContains(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContains(FieldSkillMdPath, v))
}

// SkillMdPathHasPrefix applies the HasPrefix predicate on the "skill_md_path" field.
func SkillMdPathHasPrefix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasPrefix(FieldSkillMdPath, v))
}

// SkillMdPathHasSuffix applies the HasSuffix predicate on the "skill_md_path" field.
func SkillMdPathHasSuffix(v string) predicate.Skill {
	return predicate.Skill(sql.FieldHasSuffix(FieldSkillMdPath, v))
}

// SkillMdPathIsNil applies the IsNil predicate on the "skill_md_path" field.
func SkillMdPathIsNil() predicate.Skill {
	return predicate.Skill(sql.FieldIsNull(FieldSkillMdPath))
}

// SkillMdPathNotNil applies the NotNil predicate on the "skill_md_path" field.
func SkillMdPathNotNil() predicate.Skill {
	return predicate.Skill(sql.FieldNotNull(FieldSkillMdPath))
}

// SkillMdPathEqualFold applies the EqualFold predicate on the "skill_md_path" field.
func SkillMdPathEqualFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldEqualFold(FieldSkillMdPath, v))
}

// SkillMdPathContainsFold applies the ContainsFold predicate on the "skill_md_path" field.
func SkillMdPathContainsFold(v string) predicate.Skill {
	return predicate.Skill(sql.FieldContainsFold(FieldSkillMdPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Skill {
	return predicate.Skill(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeams applies the HasEdge predicate on the "teams" edge.
func HasTeams() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, TeamsTable, TeamsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamsWith applies the HasEdge predicate on the "teams" edge with a given conditions (other predicates).
func HasTeamsWith(preds ...predicate.Team) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, GroupsTable, GroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.TeamGroup) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamSkills applies the HasEdge predicate on the "team_skills" edge.
func HasTeamSkills() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamSkillsTable, TeamSkillsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamSkillsWith applies the HasEdge predicate on the "team_skills" edge with a given conditions (other predicates).
func HasTeamSkillsWith(preds ...predicate.TeamSkill) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newTeamSkillsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamGroupSkills applies the HasEdge predicate on the "team_group_skills" edge.
func HasTeamGroupSkills() predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TeamGroupSkillsTable, TeamGroupSkillsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamGroupSkillsWith applies the HasEdge predicate on the "team_group_skills" edge with a given conditions (other predicates).
func HasTeamGroupSkillsWith(preds ...predicate.TeamGroupSkill) predicate.Skill {
	return predicate.Skill(func(s *sql.Selector) {
		step := newTeamGroupSkillsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Skill) predicate.Skill {
	return predicate.Skill(sql.NotPredicates(p))
}
